### ISSUE TITLE
mrw_prop does not support the current game (gta5)

### ISSUE THREAD

**Issue by al3x-ds** [Morow73/mrw_prop#1]
Hello, 

I found your mrw_prop script really interesting and wanted to try it on my server. 

Here is the problem: 
Warning : Resource mrw_prop does not support the current game (gta5)
Couldn't start resource mrw_prop.

Beside that, the esx_drp_garage script works very well, I was looking for one like this one.

i'm new to fivem and i don't know much about fxmanifest.lua

Thank you.

**Comment by Morow73** [comment]
Hello,

download the latest version or use a __resource.lua
